### ISSUE TITLE
Update Feds.py

### ISSUE THREAD

**Issue by ecriminals** [addi00000/feds.py#2]
Please update `Feds.Py` to include the updated user data fetching.

**Comment by addi00000** [comment]
lowkey forgot how pip packages work. probably going to make this package better since bored

**Comment by addi00000** [comment]
nah
we good

**Comment by addi00000** [comment]
https://pypi.org/project/feds.py/1.3/

**Comment by addi00000** [comment]
going to test  now

**Comment by addi00000** [comment]
raising 

```
Traceback (most recent call last):
  File "C:\Users\addis\code\feds.py\tests\test.py", line 4, in <module>
    data = feds.fetch('https://feds.lol/2').get_data()
  File "C:\Users\addis\AppData\Local\Programs\Python\Python310\lib\site-packages\feds\fetch.py", line 33, in get_data
    "audio": self.get_audio(),
  File "C:\Users\addis\AppData\Local\Programs\Python\Python310\lib\site-packages\feds\fetch.py", line 65, in get_audio
    return self.soup.find("iframe")["src"].split("?&theme=0")[0]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by addi00000** [comment]
ill fix it

**Comment by addi00000** [comment]
that one is feds.lol/2 but i also tested /1

**Comment by addi00000** [comment]
cool that works
going to push
